# This file is generated by scripts/render-homebrew-formula.sh during release.
# Keep this placeholder in-repo so local tooling has a predictable path.

class Jet < Formula
  desc "Statically-typed systems programming language with Python-like syntax"
  homepage "https://github.com/Icarus603/jet"
  url "https://github.com/Icarus603/jet/archive/refs/tags/v0.0.0.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"
  head "https://github.com/Icarus603/jet.git", branch: "main"

  depends_on "llvm@21" => :build
  depends_on "rust" => :build

  def install
    llvm = Formula["llvm@21"]
    ENV["LLVM_SYS_211_PREFIX"] = llvm.opt_prefix.to_s

    system "cargo", "build", "--release", "--package", "jet-cli"
    bin.install "target/release/jet"
    pkgshare.install "examples" if Dir.exist?("examples")
  end

  test do
    assert_match "The Jet programming language", shell_output("#{bin}/jet --help")
  end
end
